<div>
    <h2>Dependancy Example</h2>
</div>

<p><?= $block->getMain()->getId() ?></p>

<p><?= $block->getMain()->getInjectable()->getId() ?></p>

<p><?= $block->getMain()->getNonInjectable()->getId() ?></p>

<p><?= $block->getMain()->getAbstractUtil()->getName() ?></p>

<p><?= $block->getMain()->getHeavyOperation()->getName() ?></p>

<p><?= $block->getMain()->getDefaultName()->getName() ?></p>

<p><?= $block->getMain()->getDefaultName()->getName() ?></p>

<p><?= $block->getMain()->getOptionalName()->getName() ?></p>

<p><?= $block->getMain()->getMethodInjectionName() ?></p>