<?php 

/** @var \Playlist\LayoutExample\Block\Layout\Index $block */

?>


<h2><?= $block->getSubtitles(); ?></h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam obcaecati deserunt reprehenderit, dignissimos veritatis natus tenetur quasi perspiciatis fuga corporis. Corporis animi ducimus nulla facere quasi asperiores veritatis earum atque.</p>

<?= $block->getChildHtml('layout_note'); ?>

<?= $block->getNodeHtmllll(); ?>